SELECT
    TYPECOM::VARCHAR AS TYPECOM,
    COM::VARCHAR AS COM,
    REG::SMALLINT AS REG,
    DEP::VARCHAR AS DEP,
    CTCD::VARCHAR AS CTCD,
    ARR::VARCHAR AS ARR,
    TNCC::SMALLINT AS TNCC,
    NCC::VARCHAR AS NCC,
    NCCENR::VARCHAR AS NCCENR,
    LIBELLE::VARCHAR AS LIBELLE,
    CAN::VARCHAR AS CAN,
    COMPARENT::VARCHAR AS COMPARENT,
    DE_PARTITION::SMALLINT AS DE_PARTITION
FROM {{ source('communes', 'cog_communes') }}
