SELECT
    cddept::VARCHAR(3) AS cddept,
    cdreseau::VARCHAR(9) AS cdreseau,
    inseecommuneprinc::VARCHAR(5) AS inseecommuneprinc,
    nomcommuneprinc::VARCHAR AS nomcommuneprinc,
    cdreseauamont::VARCHAR(9) AS cdreseauamont,
    nomreseauamont::VARCHAR AS nomreseauamont,
    REPLACE(pourcentdebit, ' %', '')::TINYINT AS pourcentdebit,
    referenceprel::VARCHAR(11) AS referenceprel,
    dateprel::DATE AS dateprel,
    heureprel::VARCHAR AS heureprel,
    conclusionprel::VARCHAR AS conclusionprel,
    ugelib::VARCHAR AS ugelib,
    distrlib::VARCHAR AS distrlib,
    moalib::VARCHAR AS moalib,
    plvconformitebacterio::VARCHAR(1) AS plvconformitebacterio,
    plvconformitechimique::VARCHAR(1) AS plvconformitechimique,
    plvconformitereferencebact::VARCHAR(1) AS plvconformitereferencebact,
    plvconformitereferencechim::VARCHAR(1) AS plvconformitereferencechim,
    de_partition::SMALLINT AS de_partition
FROM {{ source('edc', 'edc_prelevements') }}
